name: Build VOID Portable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller --noconsole --onefile --icon="New_void_icon.ico" --name "VOID- Sending App" --collect-submodules xlwt --hidden-import "xlwt" --hidden-import "pandas" --hidden-import "openpyxl" --hidden-import "xlrd" --hidden-import "PyPDF2" --hidden-import "win32com" --hidden-import "pythoncom" --hidden-import "fitz" --hidden-import "PIL" main.py

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: VOID-Sending-App-Portable
        path: dist/VOID- Sending App.exe